version: '2.2'
services:
  postgres-db:
    build: postgres_db
    container_name: postgres-db
    restart: always
    hostname: dbhost
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 30s
      retries: 3
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: ./postgres_db.env

volumes:
  db_data:
